Problem Statement 1:
Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre- Theophile Vandermonde.


In [11]:
    def vander(x, N=None, increasing=False):
        x = asarray(x)
        if x.ndim != 1:
            raise ValueError("x must be a one-dimensional array or sequence.")
        if N is None:
            N = len(x)

        v = empty((len(x), N), dtype=promote_types(x.dtype, int))
        tmp = v[:, ::-1] if not increasing else v

        if N > 0:
            tmp[:, 0] = 1
        if N > 1:
            tmp[:, 1:] = x[:, None]
            multiply.accumulate(tmp[:, 1:], out=tmp[:, 1:], axis=1)
        return v

In [13]:
>>> x = np.array([1, 2, 3, 5])
>>> N = 3
>>> np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [14]:
>>> np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]], dtype=int32)

In [15]:
>>> x = np.array([1, 2, 3, 5])
>>> np.vander(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [16]:
>>> np.vander(x, increasing=True)


array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

The determinant of a square Vandermonde matrix is the product of the differences between the values of the input vector:

In [17]:
>>> np.linalg.det(np.vander(x))

48.00000000000003

In [18]:
>>> (5-3)*(5-2)*(5-1)*(3-2)*(3-1)*(2-1)

48